name: Dev Build
run-name: Build on branch ${{github.ref_name}} triggered by ${{github.actor}}

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  DEPLOY_ENGINE_APP: ${{ vars.DEPLOY_ENGINE_APP }}

jobs:
  dev_build:
    runs-on: [market-runner]
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "adopt"
          cache: "maven"
          overwrite-settings: false
      - name: Build maven
        id: build-maven
        shell: sh
        run: |
          modules=("bpmn-statistic" "bpmn-statistic-demo")
          builtModules=()
          filesChange=$(git diff --name-only HEAD HEAD^)
          for module in ${modules[@]}
          do
            if [[ "$filesChange" =~ .*"$module".* || "${{github.event.inputs.modulesMustBeBuilt}}" =~ .*"$module".* ]]; then
              builtModules+=("$module")
              mvn clean install -f $module/pom.xml
            fi
          done
          echo BUILT_MODULES=${builtModules[@]} >> $GITHUB_OUTPUT
      - name: Archive build artifact
        uses: actions/upload-artifact@v3
        with:
          name: bpmn-statistic-artifacts
          path: |
            */target/*.iar
      - name: Deploy build
        shell: sh
        run: |
          engineDir=/var/tools/ivy/10
          engine=${{github.event.inputs.engine}}
          if [[ ! -z $engine ]]; then
            engineDir=c:/tools/ivy-server/${engine}/engine
          fi
          for module in ${builtModules[@]}
          do
            mvn com.axonivy.ivy.ci:project-build-plugin:10.0.14:deploy-to-engine -f $module/pom.xml -Divy.deploy.engine.app=${{env.DEPLOY_ENGINE_APP}} -Divy.deploy.engine.dir=${engineDir} -Divy.test.engine=MODIFY_EXISTING -Divy.deploy.target.version=RELEASED -Divy.deploy.timeout.seconds=120
          done