# The xml command in this script is using xmlstartlet(https://xmlstar.sourceforge.net)

name: Dev Build
run-name: Build on branch ${{github.ref_name}} triggered by ${{github.actor}}

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  dev_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "adopt"
          cache: "maven"
          overwrite-settings: false
      - name: Build maven
        id: build-maven
        run: |
          modules=("bpmn-statistic" "bpmn-statistic-demo")
          for module in ${modules[@]}
          do
            mvn clean install -f $module/pom.xml
          done
          echo BUILT_MODULES=${modules[@]} >> $GITHUB_OUTPUT
      - name: Archive build artifact
        run: |
          zip -r bpmn-statistic-artifacts.zip */target/*.iar
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: bpmn-statistic-artifacts
          path: bpmn-statistic-artifacts.zip
      - name: Deploy build
        run: |
          mvn com.axonivy.ivy.ci:project-build-plugin:10.0.14:deploy-to-engine -Divy.deploy.file=bpmn-statistic-artifacts.zip -Divy.deploy.method=HTTP -Divy.deploy.engine.url=http://10.193.8.78:8080 -Divy.deploy.engine.app=BPMN
