name: Dev Build
run-name: Build on branch ${{github.ref_name}} triggered by ${{github.actor}}

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  dev_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "adopt"
          cache: "maven"
          overwrite-settings: false
      - name: Build maven
        id: build-maven
        run: |
          modules=("bpmn-statistic" "bpmn-statistic-demo")
          for module in ${modules[@]}
          do
            mvn clean install -f $module/pom.xml
          done
          echo BUILT_MODULES=${modules[@]} >> $GITHUB_OUTPUT
      - name: Archive build artifact
        run: |
          zip -r bpmn-statistic-artifacts.zip */target/*.iar
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: bpmn-statistic-artifacts
          path: bpmn-statistic-artifacts.zip
      - name: Deploy build
        run: |
          curl --location 'http://10.193.8.78:8080/system/api/apps/BPMN-STATISTIC' \
          --header 'X-Requested-By: ivy' \
          --header 'Authorization: Basic b2N0b3B1czpXNHc0QENIJA==' \
          --header 'Cookie: JSESSIONID=961EBE8FC3011F9B096B30245993EDB2' \
          --form 'fileToDeploy=@"bpmn-statistic.zip"'
