name: Dev Build
run-name: Build on branch ${{github.ref_name}} triggered by ${{github.actor}}

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  dev_build:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: marketplace.server.ivy-cloud.com
        username: octopus-actions
        key: ${{ secrets.KEY }}
        script: whoami
